In [1]:
# IMPORTAMOS LIBRERIAS
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import mysql.connector

pd.set_option('display.max_columns', None)

In [3]:
# DEFINIR LA ESTRUCTURA DE LA BBDD

In [4]:
# Crear la base de datos
cnx = mysql.connector.connect(
    user="root",
    password="AlumnaAdalab",
    host="127.0.0.1",
    auth_plugin='mysql_native_password'
)

cursor = cnx.cursor()
query_create_bd = "CREATE SCHEMA IF NOT EXISTS `ABCCorporation (M3T3)`"

cursor.execute(query_create_bd)

In [7]:

# Crear Tablas

# Table `ABCCorporation (M3T3)`.`PERSONAL_INFO`
# -----------------------------------------------------

query_create_table_personal = """
CREATE TABLE IF NOT EXISTS `ABCCorporation (M3T3)`.`PERSONAL_INFO` (
  `IdEmployee` INT NOT NULL,
  `EmployeeNumber` INT NULL,
  `Age` INT NULL,
  `DateBirth` INT NULL,
  `Gender` VARCHAR(45) NULL,
  `MaritalStatus` VARCHAR(45) NULL,
  `DistanceFromHome` INT NULL,
  `Education` INT NULL,
  `EducationField` VARCHAR(100) NULL,
  PRIMARY KEY (`IdEmployee`))
"""
cursor.execute(query_create_table_personal)


# Table `ABCCorporation (M3T3)`.`EMPLOYEE_SATISFACTION`
# ----------------------------------------

query_create_table_satisfaction = """
CREATE TABLE IF NOT EXISTS `ABCCorporation (M3T3)`.`EMPLOYEE_SATISFACTION` (
  `IdEmployeeSatisfaction` INT NOT NULL,
  `EnvironmentSatisfaction` INT NULL,
  `JobInvolvement` INT NULL,
  `JobSatisfaction` INT NULL,
  `RelationshipSatisfaction` INT NULL,
  `WorkLifeBalance` INT NULL,
  PRIMARY KEY (`IdEmployeeSatisfaction`))

"""

cursor.execute(query_create_table_satisfaction)


# Table `ABCCorporation (M3T3)`.`JOB_DATA`
# -----------------------------------------------------

query_create_table_job = """
CREATE TABLE IF NOT EXISTS `ABCCorporation (M3T3)`.`JOB_DATA` (
  `IdJobData` INT NOT NULL,
  `Attrition` VARCHAR(45) NULL,
  `JobLevel` INT NULL,
  `JobRole` VARCHAR(100) NULL,
  `NumCompaniesWorked` INT NULL,
  `TotalWorkingYears` INT NULL,
  `YearsAtCompany` INT NULL,
  `YearsSinceLastPromotion` INT NULL,
  `YearsWithCurrManager` INT NULL,
  PRIMARY KEY (`IdJobData`))
"""

cursor.execute(query_create_table_job)


# Table `ABCCorporation (M3T3)`.`SALARY`
# -----------------------------------------------------

query_create_table_salary = """
CREATE TABLE IF NOT EXISTS `ABCCorporation (M3T3)`.`SALARY` (
  `IdSalary` INT NOT NULL,
  `HourlyRate` FLOAT NULL,
  `DailyRate` FLOAT NULL,
  `MonthlyRate` FLOAT NULL,
  `MonthlyIncome` FLOAT NULL,
  `PercentSalaryHike` INT NULL,
  PRIMARY KEY (`IdSalary`))
  
"""

cursor.execute(query_create_table_salary)

# Table `ABCCorporation (M3T3)`.`JOB_EXTRAS`
# -----------------------------------------------------

query_create_table_extras = """
CREATE TABLE IF NOT EXISTS `ABCCorporation (M3T3)`.`JOB_EXTRAS` (
  `IdJobExtras` INT NOT NULL,
  `OverTime` VARCHAR(45) NULL,
  `BusinessTravel` VARCHAR(45) NULL,
  `StockOptionLevel` INT NULL,
  `TrainingTimesLastYear` INT NULL,
  `RemoteWork` TINYINT NULL,
  PRIMARY KEY (`IdJobExtras`))

"""

cursor.execute(query_create_table_extras)

# Table `ABCCorporation (M3T3)`.`UNION`
# -----------------------------------------------------

query_create_table_union = """
CREATE TABLE IF NOT EXISTS `ABCCorporation (M3T3)`.`UNION` (
  `IdUnion` INT NOT NULL,
  `PERSONAL_INFO_IdEmployee` INT NOT NULL,
  `EMPLOYEE_SATISFACTION_IdEmployeeSatisfaction` INT NOT NULL,
  `JOB_DATA_IdJobData` INT NOT NULL,
  `SALARY_IdSalary` INT NOT NULL,
  `JOB_EXTRAS_IdJobExtras` INT NOT NULL,
  PRIMARY KEY (`IdUnion`, `PERSONAL_INFO_IdEmployee`, `EMPLOYEE_SATISFACTION_IdEmployeeSatisfaction`, `JOB_DATA_IdJobData`, `SALARY_IdSalary`, `JOB_EXTRAS_IdJobExtras`),
  INDEX `fk_UNION_PERSONAL_INFO_idx` (`PERSONAL_INFO_IdEmployee` ASC) VISIBLE,
  INDEX `fk_UNION_EMPLOYEE_SATISFACTION1_idx` (`EMPLOYEE_SATISFACTION_IdEmployeeSatisfaction` ASC) VISIBLE,
  INDEX `fk_UNION_JOB_DATA1_idx` (`JOB_DATA_IdJobData` ASC) VISIBLE,
  INDEX `fk_UNION_SALARY1_idx` (`SALARY_IdSalary` ASC) VISIBLE,
  INDEX `fk_UNION_JOB_EXTRAS1_idx` (`JOB_EXTRAS_IdJobExtras` ASC) VISIBLE,
  CONSTRAINT `fk_UNION_PERSONAL_INFO`
    FOREIGN KEY (`PERSONAL_INFO_IdEmployee`)
    REFERENCES `ABCCorporation (M3T3)`.`PERSONAL_INFO` (`IdEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UNION_EMPLOYEE_SATISFACTION1`
    FOREIGN KEY (`EMPLOYEE_SATISFACTION_IdEmployeeSatisfaction`)
    REFERENCES `ABCCorporation (M3T3)`.`EMPLOYEE_SATISFACTION` (`IdEmployeeSatisfaction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UNION_JOB_DATA1`
    FOREIGN KEY (`JOB_DATA_IdJobData`)
    REFERENCES `ABCCorporation (M3T3)`.`JOB_DATA` (`IdJobData`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UNION_SALARY1`
    FOREIGN KEY (`SALARY_IdSalary`)
    REFERENCES `ABCCorporation (M3T3)`.`SALARY` (`IdSalary`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UNION_JOB_EXTRAS1`
    FOREIGN KEY (`JOB_EXTRAS_IdJobExtras`)
    REFERENCES `ABCCorporation (M3T3)`.`JOB_EXTRAS` (`IdJobExtras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
"""

cursor.execute(query_create_table_union)